// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricsService creates a new instance of MockMetricsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsService {
	mock := &MockMetricsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricsService is an autogenerated mock type for the MetricsService type
type MockMetricsService struct {
	mock.Mock
}

type MockMetricsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsService) EXPECT() *MockMetricsService_Expecter {
	return &MockMetricsService_Expecter{mock: &_m.Mock}
}

// Counter provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) Counter(name string) (int64, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Counter")
	}

	var r0 int64
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (int64, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int64); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockMetricsService_Counter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Counter'
type MockMetricsService_Counter_Call struct {
	*mock.Call
}

// Counter is a helper method to define mock.On call
//   - name string
func (_e *MockMetricsService_Expecter) Counter(name any) *MockMetricsService_Counter_Call {
	return &MockMetricsService_Counter_Call{Call: _e.mock.On("Counter", name)}
}

func (_c *MockMetricsService_Counter_Call) Run(run func(name string)) *MockMetricsService_Counter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsService_Counter_Call) Return(n int64, b bool) *MockMetricsService_Counter_Call {
	_c.Call.Return(n, b)
	return _c
}

func (_c *MockMetricsService_Counter_Call) RunAndReturn(run func(name string) (int64, bool)) *MockMetricsService_Counter_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrUpdateCounter provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) CreateOrUpdateCounter(name string, value int64) {
	_mock.Called(name, value)
	return
}

// MockMetricsService_CreateOrUpdateCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateCounter'
type MockMetricsService_CreateOrUpdateCounter_Call struct {
	*mock.Call
}

// CreateOrUpdateCounter is a helper method to define mock.On call
//   - name string
//   - value int64
func (_e *MockMetricsService_Expecter) CreateOrUpdateCounter(name any, value any) *MockMetricsService_CreateOrUpdateCounter_Call {
	return &MockMetricsService_CreateOrUpdateCounter_Call{Call: _e.mock.On("CreateOrUpdateCounter", name, value)}
}

func (_c *MockMetricsService_CreateOrUpdateCounter_Call) Run(run func(name string, value int64)) *MockMetricsService_CreateOrUpdateCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsService_CreateOrUpdateCounter_Call) Return() *MockMetricsService_CreateOrUpdateCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsService_CreateOrUpdateCounter_Call) RunAndReturn(run func(name string, value int64)) *MockMetricsService_CreateOrUpdateCounter_Call {
	_c.Run(run)
	return _c
}

// CreateOrUpdateGauge provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) CreateOrUpdateGauge(name string, value float64) {
	_mock.Called(name, value)
	return
}

// MockMetricsService_CreateOrUpdateGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateGauge'
type MockMetricsService_CreateOrUpdateGauge_Call struct {
	*mock.Call
}

// CreateOrUpdateGauge is a helper method to define mock.On call
//   - name string
//   - value float64
func (_e *MockMetricsService_Expecter) CreateOrUpdateGauge(name any, value any) *MockMetricsService_CreateOrUpdateGauge_Call {
	return &MockMetricsService_CreateOrUpdateGauge_Call{Call: _e.mock.On("CreateOrUpdateGauge", name, value)}
}

func (_c *MockMetricsService_CreateOrUpdateGauge_Call) Run(run func(name string, value float64)) *MockMetricsService_CreateOrUpdateGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsService_CreateOrUpdateGauge_Call) Return() *MockMetricsService_CreateOrUpdateGauge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetricsService_CreateOrUpdateGauge_Call) RunAndReturn(run func(name string, value float64)) *MockMetricsService_CreateOrUpdateGauge_Call {
	_c.Run(run)
	return _c
}

// Gauge provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) Gauge(name string) (float64, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Gauge")
	}

	var r0 float64
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (float64, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) float64); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockMetricsService_Gauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Gauge'
type MockMetricsService_Gauge_Call struct {
	*mock.Call
}

// Gauge is a helper method to define mock.On call
//   - name string
func (_e *MockMetricsService_Expecter) Gauge(name any) *MockMetricsService_Gauge_Call {
	return &MockMetricsService_Gauge_Call{Call: _e.mock.On("Gauge", name)}
}

func (_c *MockMetricsService_Gauge_Call) Run(run func(name string)) *MockMetricsService_Gauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricsService_Gauge_Call) Return(f float64, b bool) *MockMetricsService_Gauge_Call {
	_c.Call.Return(f, b)
	return _c
}

func (_c *MockMetricsService_Gauge_Call) RunAndReturn(run func(name string) (float64, bool)) *MockMetricsService_Gauge_Call {
	_c.Call.Return(run)
	return _c
}

// Metrics provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) Metrics() map[string]interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metrics")
	}

	var r0 map[string]interface{}
	if returnFunc, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	return r0
}

// MockMetricsService_Metrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metrics'
type MockMetricsService_Metrics_Call struct {
	*mock.Call
}

// Metrics is a helper method to define mock.On call
func (_e *MockMetricsService_Expecter) Metrics() *MockMetricsService_Metrics_Call {
	return &MockMetricsService_Metrics_Call{Call: _e.mock.On("Metrics")}
}

func (_c *MockMetricsService_Metrics_Call) Run(run func()) *MockMetricsService_Metrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetricsService_Metrics_Call) Return(stringToIfaceVal map[string]interface{}) *MockMetricsService_Metrics_Call {
	_c.Call.Return(stringToIfaceVal)
	return _c
}

func (_c *MockMetricsService_Metrics_Call) RunAndReturn(run func() map[string]interface{}) *MockMetricsService_Metrics_Call {
	_c.Call.Return(run)
	return _c
}
