// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Counters provides a mock function for the type MockStorage
func (_mock *MockStorage) Counters() map[string]int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Counters")
	}

	var r0 map[string]int64
	if returnFunc, ok := ret.Get(0).(func() map[string]int64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}
	return r0
}

// MockStorage_Counters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Counters'
type MockStorage_Counters_Call struct {
	*mock.Call
}

// Counters is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Counters() *MockStorage_Counters_Call {
	return &MockStorage_Counters_Call{Call: _e.mock.On("Counters")}
}

func (_c *MockStorage_Counters_Call) Run(run func()) *MockStorage_Counters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Counters_Call) Return(stringToInt64 map[string]int64) *MockStorage_Counters_Call {
	_c.Call.Return(stringToInt64)
	return _c
}

func (_c *MockStorage_Counters_Call) RunAndReturn(run func() map[string]int64) *MockStorage_Counters_Call {
	_c.Call.Return(run)
	return _c
}

// Gauges provides a mock function for the type MockStorage
func (_mock *MockStorage) Gauges() map[string]float64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Gauges")
	}

	var r0 map[string]float64
	if returnFunc, ok := ret.Get(0).(func() map[string]float64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}
	return r0
}

// MockStorage_Gauges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Gauges'
type MockStorage_Gauges_Call struct {
	*mock.Call
}

// Gauges is a helper method to define mock.On call
func (_e *MockStorage_Expecter) Gauges() *MockStorage_Gauges_Call {
	return &MockStorage_Gauges_Call{Call: _e.mock.On("Gauges")}
}

func (_c *MockStorage_Gauges_Call) Run(run func()) *MockStorage_Gauges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_Gauges_Call) Return(stringToFloat64 map[string]float64) *MockStorage_Gauges_Call {
	_c.Call.Return(stringToFloat64)
	return _c
}

func (_c *MockStorage_Gauges_Call) RunAndReturn(run func() map[string]float64) *MockStorage_Gauges_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCounter provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateCounter(name string, delta int64) {
	_mock.Called(name, delta)
	return
}

// MockStorage_UpdateCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCounter'
type MockStorage_UpdateCounter_Call struct {
	*mock.Call
}

// UpdateCounter is a helper method to define mock.On call
//   - name string
//   - delta int64
func (_e *MockStorage_Expecter) UpdateCounter(name any, delta any) *MockStorage_UpdateCounter_Call {
	return &MockStorage_UpdateCounter_Call{Call: _e.mock.On("UpdateCounter", name, delta)}
}

func (_c *MockStorage_UpdateCounter_Call) Run(run func(name string, delta int64)) *MockStorage_UpdateCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateCounter_Call) Return() *MockStorage_UpdateCounter_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorage_UpdateCounter_Call) RunAndReturn(run func(name string, delta int64)) *MockStorage_UpdateCounter_Call {
	_c.Run(run)
	return _c
}

// UpdateGauge provides a mock function for the type MockStorage
func (_mock *MockStorage) UpdateGauge(name string, value float64) {
	_mock.Called(name, value)
	return
}

// MockStorage_UpdateGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGauge'
type MockStorage_UpdateGauge_Call struct {
	*mock.Call
}

// UpdateGauge is a helper method to define mock.On call
//   - name string
//   - value float64
func (_e *MockStorage_Expecter) UpdateGauge(name any, value any) *MockStorage_UpdateGauge_Call {
	return &MockStorage_UpdateGauge_Call{Call: _e.mock.On("UpdateGauge", name, value)}
}

func (_c *MockStorage_UpdateGauge_Call) Run(run func(name string, value float64)) *MockStorage_UpdateGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_UpdateGauge_Call) Return() *MockStorage_UpdateGauge_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStorage_UpdateGauge_Call) RunAndReturn(run func(name string, value float64)) *MockStorage_UpdateGauge_Call {
	_c.Run(run)
	return _c
}
